# Generated by Django 2.2 on 2022-04-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aboutpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutSection',
            new_name='About',
        ),
    ]
