# Generated by Django 2.2 on 2022-04-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_cartmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
