# Generated by Django 2.2 on 2022-04-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20220401_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='order',
            field=models.BooleanField(default=False),
        ),
    ]
