# Generated by Django 2.2 on 2022-04-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_cartmodel_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='quantity',
        ),
    ]
