# Generated by Django 2.2 on 2022-04-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_remove_wishlist_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phonenumber',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
