# Generated by Django 2.2 on 2022-04-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_customuser_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
