# Generated by Django 2.2 on 2022-04-09 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20220409_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='post_date',
            new_name='created',
        ),
    ]
